### ISSUE TITLE
React Native future support

### ISSUE THREAD

**Issue by AaronVasquez** [cyclejs/react-native#11]
Love the simplicity of cycle.js over redux, but still being new to react native, I am a little worried react native won't be a priority for cycle.js support. What is the plan for integrating with react native?

**Comment by staltz** [comment]
It all depends on our time availability to tackle it. Tylor was going to update cycle.js to work with the latest RN, but his work life situation changed a lot. I have to say that I am soon probably going to use RN with Cycle.js, so I'll definitely have to update this package. Worry not, it will happen.
