### ISSUE TITLE
rendering issue on iOS , @cycle/run, delayed creation

### ISSUE THREAD

**Issue by barelyhuman** [cyclejs/react-native#24]
**issue**
`run` doesn't work as expected as nothing is shown on the screen unless a delay is added and `setup` is used instead of run. 

eg: 
```js
const prog = setup(main, {
  react: makeReactNativeDriver(appName),
});

setTimeout(() => {
  prog.run()
}, 1);
```

This was discussed in a PR previously and I finally got time to review the cause. 

It's because of the weird implementation of `setImmediate` on the iOS side of things, which never really works as needed, or to be fair there's no scheduling at all and things execute literally immediately and the contextual wait never really happens.

Which in turn makes it impossible for `quicktask` to execute the addition of listeners which is done in `@cycle/run`

A quick fix for this on the user side is to change this in the `index.js` code right before `run()`

```js
global.setImmediate = fn => setTimeout(fn, 1);
// or 
// global.queueMicrotask = fn => setTimeout(fn, 1);

run(main, {
  react: makeReactNativeDriver(appName),
});
```

It's not a graceful solution but I don't think we need to patch `quicktask` to change it's priority but instead if `run` could just use timeout, that'd work in all places? except when `process` is available. 

Or if there's a better solution, we could go with that

**Comment by staltz** [comment]
Perhaps the import of `@cycle/react-native` could shim `global.queueMicrotask` or then perhaps this shimming could be explicit and mentioned in the README.

**Comment by barelyhuman** [comment]
Where would you prefer it? 

I'd personally go for adding this shim in the user code

**Comment by staltz** [comment]
> I'd personally go for adding this shim in the user code

Yeah, adding it to the README is probably an easy start, we can do other solutions in the future.

**Comment by barelyhuman** [comment]
#25
